### ISSUE TITLE
Issue installing requirements

### ISSUE THREAD

**Issue by abundov** [4w4k3/KnockMail#10]
└─$ sudo pip install -r requeriments.txt                                                                                                      1 ⨯
Collecting validate_email
  Downloading validate_email-1.3.tar.gz (4.7 kB)
Collecting pyDNS
  Downloading pydns-2.3.6.tar.gz (28 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-efytzi12/pyDNS/setup.py'"'"'; __file__='"'"'/tmp/pip-install-efytzi12/pyDNS/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7j8z6e4m                                
         cwd: /tmp/pip-install-efytzi12/pyDNS/                                                                                                    
    Complete output (7 lines):                                                                                                                    
    Traceback (most recent call last):                                                                                                            
      File "<string>", line 1, in <module>                                                                                                        
      File "/tmp/pip-install-efytzi12/pyDNS/setup.py", line 12, in <module>                                                                       
        import DNS                                                                                                                                
      File "/tmp/pip-install-efytzi12/pyDNS/DNS/__init__.py", line 14, in <module>                                                                
        import Type,Opcode,Status,Class                                                                                                           
    ModuleNotFoundError: No module named 'Type'                                                                                                   
    ----------------------------------------                                                                                                      
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by kaliblackking** [comment]
Same problem as me

**Comment by archidote** [comment]
same here

**Comment by novitae** [comment]
For the requirements, try to change pyDNS in requirements.txt by py3DNS, pyDNS doesn't work on Python3

**Comment by Tanveer-boat** [comment]
Installation problem

**Comment by Allinfoplug** [comment]
How to install the software sir?

**Comment by token-hub** [comment]
I also encountered this issue, In my case I just manually installed the packages inside the requirement.txt. I don't know if it's the right thing to do since I'm not familiar with python, but it works in my case.

pip install validate_email
pip install pyDNS
